name: Update HTML from Issue

# Issueが作成されたときにこのワークフローが実行される
on:
  issues:
    types: [opened]

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout repository content
      uses: actions/checkout@v2

    # 2. Issueの内容を取得し、HTMLに反映
    - name: Update HTML with Issue Content
      run: |
        echo "Fetching issue content and updating HTML file..."

        # Issueの内容を取得
        ISSUE_BODY="${{ github.event.issue.body }}"
        
        # Issueタイトルを取得（研究室名に使用）
        ISSUE_TITLE="${{ github.event.issue.title }}"

        # HTMLファイルのパス
        HTML_FILE="index.html"

        # HTMLファイルにIssueの内容を追加
        echo "
        <div class='lab-container'>
          <h2>研究室名: ${ISSUE_TITLE}</h2>
          <p><strong>紹介文:</strong> ${ISSUE_BODY}</p>
        </div>
        " >> $HTML_FILE

    # 3. 変更をコミットしてプッシュ
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add $HTML_FILE
        git commit -m "Updated HTML with new lab info from Issue #${{ github.event.issue.number }}"
        git push
