name: Update HTML from Issue

# Issueが作成されたときにこのワークフローが実行される
on:
  issues:
    types: [opened]

# GITHUB_TOKENにリポジトリへの書き込み権限を付与
permissions:
  contents: write

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository content
        uses: actions/checkout@v3  # バージョンをv3に更新

      # 2. Issueの内容を取得し、HTMLに反映
      - name: Update HTML with Issue Content
        run: |
          echo "Fetching issue content and updating HTML file..."
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"

          # HTMLファイルのパス
          HTML_FILE="index.html"

          # HTMLファイル全体を上書きする
          cat <<EOF > $HTML_FILE
          <!DOCTYPE html>
          <html lang='ja'>
          <head>
              <meta charset='UTF-8'>
              <meta name='viewport' content='width=device-width, initial-scale=1.0'>
              <title>研究室情報サイト</title>
              <style>
                  @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
                  body { font-family: 'Roboto', sans-serif; background-color: #f0f4f8; margin: 0; padding: 0; color: #333; }
                  h1 { text-align: center; margin-top: 50px; font-size: 2.5em; color: #2c3e50; }
                  .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
                  .lab-container { background: #fff; padding: 20px; margin-bottom: 30px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); display: flex; flex-direction: column; align-items: flex-start; gap: 10px; }
                  .lab-info h2 { margin-top: 0; font-size: 1.8em; color: #34495e; }
                  .lab-info p { margin: 10px 0; font-size: 1em; line-height: 1.6; color: #555; }
                  .label { font-weight: bold; color: #2980b9; }
              </style>
          </head>
          <body>
              <h1>${ISSUE_TITLE}</h1>
              <p>${ISSUE_BODY}</p>
          </body>
          </html>
          EOF

      # 3. 変更をコミットしてプッシュ
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Updated HTML with new lab info from Issue #${{ github.event.issue.number }}"
          git push
